spring:
  datasource:
   url: jdbc:h2:mem:test
   driverClassName: org.h2.Driver
   username: sa
   password:
  h2.console.enabled: true
  profiles:
    active: production
  thymeleaf:
    mode:   HTML
logging:
  level:
    org:
      springframework: INFO
server:
  port: ${PORT:5000}
